name: QA
on: pull_request
jobs:
  qa:
    name: Run QA checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts", "latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js {% raw %}${{ matrix.node-version }}{% endraw %}
        uses: actions/setup-node@v2
        with:
          node-version: {% raw %}${{ matrix.node-version }}{% endraw %}
      - name: Install the world
        run: npm install
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm test
